use Assignment2

--1)
SELECT * FROM EMP WHERE JOB = 'MANAGER';

--2)
SELECT ENAME, SAL FROM EMP WHERE SAL > 1000;

--3)
SELECT ENAME, SAL FROM EMP WHERE ENAME <> 'JAMES';

--4)
SELECT * FROM EMP WHERE ENAME LIKE 'S%';

--5)
SELECT ENAME FROM EMP WHERE ENAME LIKE '%A%';

--6)
SELECT ENAME FROM EMP WHERE ENAME LIKE '__L%';

--7)
SELECT ENAME, SAL/30 AS DAILY_SALARY FROM EMP WHERE ENAME = 'JONES';

--8)
SELECT SUM(SAL) AS TOTAL_MONTHLY_SALARY FROM EMP;

--9)
SELECT AVG(SAL * 12) AS AVG_ANNUAL_SALARY FROM EMP;

--10)
SELECT ENAME, JOB, SAL, DEPTNO FROM EMP WHERE JOB <> 'SALESMAN' AND DEPTNO = 30;

--11)
SELECT DISTINCT DEPTNO FROM EMP;

--12)
SELECT ENAME AS Employee, SAL AS "Monthly Salary" FROM EMP WHERE SAL > 1500 AND DEPTNO IN (10, 30);

--13)
SELECT ENAME, JOB, SAL FROM EMP
WHERE JOB IN ('MANAGER', 'ANALYST') AND SAL NOT IN (1000, 3000, 5000);

--14) 
SELECT ENAME, SAL, COMM FROM EMP WHERE COMM > SAL * 1.10;

--15) 
SELECT ENAME FROM EMP WHERE ENAME LIKE '%L%L%' AND (DEPTNO = 30 OR MGR_ID = 7782);

--16) 
SELECT COUNT(*) AS TOTAL_EMPLOYEES FROM EMP
WHERE DATEDIFF(YEAR, HIREDATE, GETDATE()) BETWEEN 31 AND 39;

--17) 
SELECT D.DNAME, E.ENAME FROM DEPT D JOIN EMP E ON D.DEPTNO = E.DEPTNO
ORDER BY D.DNAME ASC, E.ENAME DESC;

--18)
SELECT ENAME, DATEDIFF(YEAR, HIREDATE, GETDATE()) AS EXPERIENCE_YEARS
FROM EMP WHERE ENAME = 'MILLER';